In [2]:
#Importing necessary libraries
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
import joblib
import numpy as np

In [3]:
%run preprocessing.ipynb

[2019]


In [4]:
#Lets deal with model trainig first go with linear regression
linear_regression=LinearRegression()

In [5]:
#Here we fitted our linear regression by our training data
linear_regression.fit(X_train_lr,y_train_lr)

LinearRegression()

In [6]:
#We have predicted the value in log transformation
y_pred_log_lr=linear_regression.predict(X_value)

In [7]:
y_pred_log_lr

array([9.73890873, 8.28826961, 9.14440134, ..., 8.88343789, 9.65069014,
       8.3388359 ], shape=(3111,))

In [8]:
#The codfficents for the predicted values
linear_regression.coef_

array([ 2.95195658e-01, -6.95617043e-03, -3.19878716e-02,  6.53768622e-06,
        1.15978345e-03,  1.06703546e-04,  9.79560646e-04,  4.01605780e-03,
       -9.87897123e-04, -2.74108048e-04,  2.34297201e-01,  2.50789751e-02,
        5.17399690e-02,  5.26245528e-01,  9.19403442e-16,  4.38328097e-01,
        5.71187266e-01, -1.17864833e-01, -1.33387331e-01,  3.26719616e-01,
        6.49516434e-01, -2.48578211e-02,  4.70519923e-02,  6.93698045e-02,
       -1.70871862e-01,  4.70519923e-02, -9.32164304e-02, -1.70871862e-01,
       -2.48578211e-02,  1.72524317e-01])

In [9]:
linear_regression.intercept_

np.float64(8.630642066743667)

In [10]:
#Lets try to convert those log transformed predicted values
y_pred_lr=np.expm1(y_pred_log_lr)
y_pred_lr

array([16964.0178063 ,  3975.94656986,  9360.87941263, ...,
        7210.54061856, 15531.5039841 ,  4182.2172348 ], shape=(3111,))

In [11]:
#Now going to work with random forest
#here we dont use log_transformed data
rfr=RandomForestRegressor(n_estimators=100)

In [12]:
#lets fir our random forest regressor
rfr.fit(X_rf_xg,y_rf_xg)

RandomForestRegressor()

In [13]:
#predicted values 
y_pred_rfr=rfr.predict(X_value_rf_xg)

In [14]:
y_pred_rfr

array([14910.54      ,  9380.37      ,  3937.76      , ...,
       11216.24630952, 13692.37      ,  4823.        ], shape=(3139,))

In [15]:
#finding the feature importances
feature_importances = pd.Series(rfr.feature_importances_, index=X_train_rf_xg.columns)

In [16]:
feature_importances

Total_Stops                                  0.030053
journey_day                                  0.131569
journey_month                                0.048711
Duration_in_time                             0.461700
arrival_time_hour                            0.030874
arrival_time_minute                          0.020536
arrival_day                                  0.013704
arrival_month                                0.007583
Departure_hour                               0.025159
Departure_minute                             0.025091
Airline_Air India                            0.004729
Airline_GoAir                                0.002639
Airline_IndiGo                               0.005375
Airline_Jet Airways                          0.057578
Airline_Jet Airways Business                 0.065137
Airline_Multiple carriers                    0.018351
Airline_Multiple carriers Premium economy    0.000837
Airline_SpiceJet                             0.002880
Airline_Trujet              

In [17]:
#Now working with XGBoost mode

In [18]:
#here we fit our XGBoost model
xgb=XGBRegressor()
xgb.fit(X_rf_xg,y_rf_xg)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=None, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=None,
             n_jobs=None, num_parallel_tree=None, ...)

In [19]:
#lets make prediction with help of validation data
y_pred_xgb=xgb.predict(X_value_rf_xg)

In [20]:
y_pred_xgb

array([14052.083 ,  9933.887 ,  4039.5356, ..., 12353.151 , 14688.238 ,
        4489.3403], shape=(3139,), dtype=float32)

In [21]:
xgb.feature_importances_

array([0.02663652, 0.02748489, 0.01732165, 0.07737387, 0.00970696,
       0.00538928, 0.00933935, 0.0107701 , 0.00571845, 0.00688242,
       0.01231746, 0.02458348, 0.0463163 , 0.1373078 , 0.3915079 ,
       0.03544951, 0.00626826, 0.02391235, 0.00046668, 0.01359029,
       0.00051357, 0.00357126, 0.01958335, 0.01239955, 0.02016099,
       0.        , 0.00330579, 0.        , 0.        , 0.05212209],
      dtype=float32)

In [22]:
pd.Series(xgb.feature_importances_,index=X_train_rf_xg.columns)

Total_Stops                                  0.026637
journey_day                                  0.027485
journey_month                                0.017322
Duration_in_time                             0.077374
arrival_time_hour                            0.009707
arrival_time_minute                          0.005389
arrival_day                                  0.009339
arrival_month                                0.010770
Departure_hour                               0.005718
Departure_minute                             0.006882
Airline_Air India                            0.012317
Airline_GoAir                                0.024583
Airline_IndiGo                               0.046316
Airline_Jet Airways                          0.137308
Airline_Jet Airways Business                 0.391508
Airline_Multiple carriers                    0.035450
Airline_Multiple carriers Premium economy    0.006268
Airline_SpiceJet                             0.023912
Airline_Trujet              

In [23]:
#Now saving models
models_path="../models"
joblib.dump(rfr,os.path.join(models_path,"random_forest.pkl"))

['../models\\random_forest.pkl']

In [25]:
joblib.dump(linear_regression,os.path.join(models_path,"linear_regression.pkl"))

['../models\\linear_regression.pkl']

In [26]:
joblib.dump(xgb,os.path.join(models_path,"XGBoost.pkl"))

['../models\\XGBoost.pkl']